module.exports = {
    userRegister: 'user_register',
    userChangeName: 'user_change_name',
    userLoudSpeaker: 'user_loud_speaker',
    userUpdateLoudSpeakerSettings: 'user_update_loud_speaker_settings',
    userCreateRoom: 'user_create_room',
    userJoinRoom: 'user_join_room',
    userLeaveRoom: 'user_leave_room',
    usetGetRoomInvitation: 'user_get_room_intitation',
    userSendRoomInvitation: 'user_send_room_intitation',
    userSendMessage: 'user_send_message',
    userUpdateRoomPassword: 'user_update_room_password',
    userKickOutRoom: 'user_kick_out_room',
    userBlowUpRoom: 'user_blow_up_room',
    userSetRoomNotice: 'user_set_room_notice',
}